// import './lessons/lesson4'
// import './lessons/dom_travers'
// import './lessons/createDomElement'
// import './lessons/insertAdjacentElement'
// import './lessons/update_&_delete'
// import './lessons/cloneNode'
// import './lessons/style_in_dom'
import './lessons/event'